export const ROUTES = {
  AUTH: {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    ORGANIZATION: '/auth/organization',
  },
  DASHBOARD: {
    HOME: 'dashboard',
    CALENDAR: '/dashboard/calendar',
    CHAT: '/dashboard/chat',
    ISSUES: '/dashboard/issues',
    AGENT_PROFILES: '/dashboard/agents/profiles',
    AGENT_PROFILES_NEW: '/dashboard/agents/profiles/new',
    AGENT_TASKS: '/dashboard/agents/tasks',
    AGENT_TASKS_NEW: '/dashboard/agents/tasks/new',
    TELEGRAM_CHATS: '/dashboard/chat/telegram',
    MEETING: '/dashboard/meeting',
    TEAMS: '/dashboard/teams',
    METHODOLOGY: '/dashboard/methodology',
    STATISTICS: '/dashboard/statistics',
    FOLLOWUPS: '/dashboard/follow-ups',
    ORGANIZATION: '/dashboard/organization',
    PROFILE: '/dashboard/profile',
    SUMMARY: '/dashboard/summary',
    KANBAN: '/dashboard/kanban',
    DEBUG_LOGS: '/dashboard/debug-logs',
  },
} as const;
