export const ROUTES = {
  AUTH: {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    ORGANIZATION: '/auth/organization',
  },
  DASHBOARD: {
    HOME: 'dashboard',
    TODAY: '/dashboard/today',
    MEETINGS: '/dashboard/meetings',
    TASKS: '/dashboard/tasks',
    CALENDAR: '/dashboard/calendar',
    CHAT: '/dashboard/chat',
    ISSUES: '/dashboard/issues',
    AGENTS: '/dashboard/agents',
    AGENT_PROFILES: '/dashboard/agents/profiles',
    AGENT_PROFILES_NEW: '/dashboard/agents/profiles/new',
    AGENT_TASKS: '/dashboard/agents/tasks',
    AGENT_TASKS_NEW: '/dashboard/agents/tasks/new',
    AGENT_ACTIVITY: '/dashboard/agents/activity',
    TELEGRAM_CHATS: '/dashboard/chat/telegram',
    MEETING: '/dashboard/meeting',
    TEAMS: '/dashboard/teams',
    TEAM: (teamId: number | string) => {
      return `/dashboard/teams/${teamId}`;
    },
    METHODOLOGY: '/dashboard/methodology',
    STATISTICS: '/dashboard/statistics',
    FOLLOWUPS: '/dashboard/follow-ups',
    ORGANIZATION: '/dashboard/organization',
    PROFILE: '/dashboard/profile',
    SUMMARY: '/dashboard/summary',
    KANBAN: '/dashboard/kanban',
    DEBUG: '/dashboard/debug',
    DEBUG_LOGS: '/dashboard/debug/logs',
    DEBUG_API: '/dashboard/debug/api',
    MAIN: '/dashboard/main',
    MAIN_OVERVIEW: '/dashboard/main/overview',
    MAIN_STATISTICS: '/dashboard/main/statistics',
    ISSUES_LIST: '/dashboard/issues/list',
    ISSUES_KANBAN: '/dashboard/issues/kanban',
  },
} as const;
